kind = "DojoModel"
class_hash = "0x73f3710ff3124f6c8e376f78e9404f7256557df6c0c79876f09bd4c33e8f3d2"
original_class_hash = "0x73f3710ff3124f6c8e376f78e9404f7256557df6c0c79876f09bd4c33e8f3d2"
abi = "manifests/dev/base/abis/models/mancala_alpha-MancalaGame-628bb438.json"
tag = "mancala_alpha-MancalaGame"
manifest_name = "mancala_alpha-MancalaGame-628bb438"

[[members]]
name = "game_id"
type = "u128"
key = true

[[members]]
name = "player_one"
type = "ContractAddress"
key = false

[[members]]
name = "player_two"
type = "ContractAddress"
key = false

[[members]]
name = "current_player"
type = "ContractAddress"
key = false

[[members]]
name = "last_move"
type = "u64"
key = false

[[members]]
name = "time_between_move"
type = "u64"
key = false

[[members]]
name = "winner"
type = "ContractAddress"
key = false

[[members]]
name = "status"
type = "GameStatus"
key = false

[[members]]
name = "is_private"
type = "bool"
key = false
