[world]
name = "Mancala"
description = "Mancala is a fully on-chain PvP strategy boardgame built on Dojo."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/realm-of-ra/mancala"
seed = "mancala"

[world.socials]
x = "https://x.com/realm_of_ra"
discord = "https://discord.gg/FB2wR6uF"
github = "https://github.com/realm-of-ra/mancala"
telegram = "https://t.me/dojoengine"

[namespace]
default = "mancala"

[writers]
"mancala" = ["mancala-actions"]

[env]
rpc_url = "https://api.cartridge.gg/x/mancala-p/katana"
# Default account for katana with seed = 0
account_address = "0x127fd5f1fe78a71f8bcd1fec63e3fe2f0486b6ecd5c86a0466c3a21fa5cfcec"
private_key = "0xc5b2fcab997346f3ea1c00b002ecf6f382c5f9c9659a3894eb783c5320f912"
world_address = "0x7e6333cfb9768d94ffa94daf40d8261b27a245a154e180e8ed052781a2e1779"  # Uncomment and update this line with your world address.
ipfs_config.url = "https://ipfs.infura.io:5001"
ipfs_config.username = "2EBrzr7ZASQZKH32sl2xWauXPSA"
ipfs_config.password = "12290b883db9138a8ae3363b6739d220"
