rpc = "https://api.cartridge.gg/x/starknet/sepolia"

allowed_origins = ["*"]
# The World address to index.
world_address = "0x015963c226a157f6bfb85406f192ffd34fab5aaff678689136699200099e60fd"

# Indexing Options
[indexing]
allowed_origins = ["*"]
pending = true
transactions = true
polling_interval = 1000
contracts = [
    "erc721:0x00c489b121fdc7bf7aa71167d603de7d41184576b6ed1bae87dd7b448c4ac8cf"
]

[events]
raw = true
historical = [
    "mancala_stone-TrophyProgression",
]
